language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-prueba123' ]; then cd .. && eval "mv $currentfolder generator-prueba123" && cd generator-prueba123; fi